- name: Install apt dependencies
  become: yes
  apt:
      name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
      state: present
      update_cache: yes

- name: Add APT key for docker repository
  become: yes
  shell: "curl -fsSL https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg | apt-key add -"

- name: Add repository
  become: yes
  shell: 'echo "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} $(lsb_release -cs) stable" > /etc/apt/sources.list.d/riotkit-docker.list'

- name: Install docker from the download.docker.com repository
  become: yes
  apt:
    name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    state: present
    update_cache: yes
