- name: Install docker from main repository
  become: yes
  apt: name="docker.io" state=present update_cache=yes
  when: ansible_distribution != 'Debian'

- include: docker.debian.yml
  when: ansible_distribution == 'Debian'

- name: Delete old docker-compose from package manager
  become: yes
  apt:
      name: docker-compose
      state: absent

- name: Install required Python packages
  become: yes
  apt:
      name: ["{{ setuptools_pkg_name }}", "{{ python_pip_pkg_name }}"]
      state: present

- name: Install recent version of docker compose
  become: yes
  pip:
      name: docker-compose
      state: present

- name: Schedule a clean up for Docker images
  become: yes
  cron:
      name: "docker-clean-up"
      minute: "0"
      hour: "22"
      job: "docker container prune -f; docker image prune -f"
      day: "10"
  when: docker_schedule_clean_up|bool
