- name: Enable SSH forwarding for sudo
  become: yes
  lineinfile:
      dest: /etc/sudoers
      insertafter: '^#?\s*Defaults\s+env_keep\b'
      line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'
  tags:
      - infrastructure.basic_software.sudoers
